<template>
  <div>
    <NavBar />
    <Nuxt />
  </div>
</template>

<script>
export default {
  head() {
    return {
      title: this.$t('head.title'),
      ...this.$nuxtI18nHead({ addSeoAttributes: true }),
      meta: [
        {
          hid: 'twitter:title',
          name: 'twitter:title',
          content: this.$t('head.title'),
        },
        {
          hid: 'twitter:description',
          name: 'twitter:description',
          content: this.$t('head.description'),
        },
        {
          hid: 'twitter:image',
          name: 'twitter:image',
          content: require('@/assets/images/witnet_green.png'),
        },
        {
          hid: 'twitter:image:alt',
          name: 'twitter:image:alt',
          content: this.$t('head.title'),
        },
        {
          hid: 'og:title',
          property: 'og:title',
          content: this.$t('head.title'),
        },
        {
          hid: 'og:description',
          property: 'og:description',
          content: this.$t('head.description'),
        },
        {
          hid: 'og:image',
          property: 'og:image',
          content: require('@/assets/images/witnet_green.png'),
        },
        {
          hid: 'og:image:secure_url',
          property: 'og:image:secure_url',
          content: require('@/assets/images/witnet_green.png'),
        },
        {
          hid: 'og:image:alt',
          property: 'og:image:alt',
          content: this.$t('head.title'),
        },
      ],
    }
  },
}
</script>
<style lang="scss">
html {
  font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI',
    Roboto, 'Helvetica Neue', Arial, sans-serif;
  font-size: 16px;
  word-spacing: 1px;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  box-sizing: border-box;
  scroll-behavior: smooth;
}
html,
body {
  margin: 0;
  padding: 0;
  // use this rule to avoid show the scroll generated by the pseudo-class ::after in DecentralizedOracle.vue
  overflow-x: hidden;
}

*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
}
</style>
