<template>
  <div>
    <NavBar />
    <Nuxt />
  </div>
</template>

<script>
export default {
  head() {
    return {
      ...this.$nuxtI18nHead({ addSeoAttributes: true }),
    }
  },
}
</script>
<style lang="scss">
html {
  font-family: 'Source Sans Pro', -apple-system, BlinkMacSystemFont, 'Segoe UI',
    Roboto, 'Helvetica Neue', Arial, sans-serif;
  font-size: 16px;
  word-spacing: 0;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  box-sizing: border-box;
  scroll-behavior: smooth;
}
html,
body {
  margin: 0;
  padding: 0;
  // use this rule to avoid show the scroll generated by the pseudo-class ::after in DecentralizedOracle.vue
  overflow-x: hidden;
}

*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
}
</style>
